#!/usr/bin/env zsh
STOW_FOLDERS="bin,i3,nvim,personal,tmux,zsh,backgrounds,rofi,picom,alacritty,polybar"

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/.dotfiles
fi

pushd $DOTFILES
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    echo "stow $folder"
    stow -D $folder
    stow $folder
done
popd
